### ISSUE TITLE
Docker compose and redis

### ISSUE THREAD

**Issue by fredericoschardong** [alehuo/pyoidc-redis-session-backend-example#2]
After adding my OIDC server, I get this error regarding redis:

`server_1    | redis.exceptions.ConnectionError: Error -2 connecting to http://redis:6379. Name or service not known.`

I haven't changed anything other than the three OIDC lines. What am I missing?

**Comment by fredericoschardong** [comment]
Got it. The docker-compose.yml is misleading. It should be `SESSION_REDIS_HOST=redis` instead of `SESSION_REDIS_HOST=http://redis`.

**Comment by alehuo** [comment]
Good catch, I will update the example code!
